// <auto-generated />
namespace React_Onboarding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChequeDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChequeDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201905180409557_ChequeDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
